spring.application.name=employee-backend
server.port=8084


spring.profiles.active=oracle


spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#credentials
app.security.user:${APP_USER}
app.security.password:${APP_PASSWORD}

logging.level.root=INFO
logging.level.com.invex=DEBUG