spring.application.name=employee-backend
server.port=8084

# Define el perfil activo por defecto (H2 para el evaluador)
spring.profiles.active=oracle


# Configuración común de JPA
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#credentials
app.security.user:${APP_USER}
app.security.password:${APP_PASSWORD}